### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by linakherchi** [Tului2020/prince-john#2]
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-in-person/full-stack-project/mvp-checklist) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

**Comment by linakherchi** [comment]
Please work on the formatting and reassign this issue back to me so that I can review each one of your MVPs more thoroughly.

Thanks

**Comment by Tului2020** [comment]
done :)

**Comment by linakherchi** [comment]
Thanks, Tului ! 

Have you thought of how are you going to implement limit calls ? It sounds challenging but if you found a simple way, I'll be curious to learn about it.

I still feel there are more important MVPs that can be prioritized. For example, you might want to have a stock show page, you might also want to implement a search functionality.

Let me know if you want to discuss it further.

**Comment by Tului2020** [comment]
Hi Lina,

That's a good question, my initial gut feeling is to setup a async JS callback that gets triggered when a stock reaches a certain price. Is that what you recommend? 

I updated the MVP list accordingly.

**Comment by linakherchi** [comment]
That callback will be triggered only when the user is on that stock's show page ? 

I like it better ! Good job !
