### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by linakherchi** [Tului2020/prince-john#3]
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

**Comment by linakherchi** [comment]
Thanks, Tului ! 

According to your MVP List, I believe you should add a watchlist table (Users can buy, sell, watch stocks of their choosing).

I also believe you should add a column in the users table to track that user's balance as they trade.

You could also add a column in the user-stock table that saves the price at which the user bought the stock. That will allow you to calculate the user gains/ losses when that user wants to sell.

Happy to discuss it further ! Please also arrange the display of the schema according to the checklist above.

Once you update your schema, please make sure to apply those updates to your state shape as well so that I can review it.

Thanks

**Comment by Tului2020** [comment]
Lina,

I made some changes, can you take a look at it when you get a chance? 

Instead of creating a watchlist table, can i make the limit calls using a async js call? Thanks!

Tului

**Comment by linakherchi** [comment]
Thanks, Tului ! 

You already have enough MVPs to not have to implement a watchlist. If you really want to implement limit calls, I would leave that as a bonus. (After you completing the referral MVP).

Let's discuss it when you complete referral MVP, as I do not believe an async call will be enough to implement this functionality ( How will that async call keep working in the background and keep track of stock prices when the app is not running ? ) . I still think it is a challenging MVP that I encourage you to explore once you have your main MVPs built.

**Comment by Tului2020** [comment]
hmmmm I think you're right. I'll leave the limit calls as a bonus, but I think I can do one of the following two things:
1. Since it is not a real stock brokerage, I can trigger a check whenever the user refreshes the page. 
2. Or I think an async call that runs in the background every 1/2 second that fetches prices and checks if the price is reached. 

The second method will be more expensive.

**Comment by linakherchi** [comment]
I like the second option !
