### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by linakherchi** [Tului2020/prince-john#5]
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

**Comment by linakherchi** [comment]
Please have your routes displayed as they are in Bluebird.

Thanks

**Comment by Tului2020** [comment]
Done :)

**Comment by linakherchi** [comment]
Thanks, Tului ! 

You still need a route to allow the user to buy/sell stocks.

**Comment by Tului2020** [comment]
That's right, how do you think i should route that?

**Comment by linakherchi** [comment]
You will need to use the user_stocks table to POST and DELETE whenever a user buys/sells stocks
