### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by linakherchi** [Tului2020/prince-john#6]
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by linakherchi** [comment]
Thanks, Tului! 
You might also need a dashboard for the user ? Not sure if that is an option in Robinhood.

**Comment by Tului2020** [comment]
Made the changes.
